# Generated by Django 5.1.3 on 2024-11-07 04:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dificultad',
            fields=[
                ('id_dificultad', models.AutoField(primary_key=True, serialize=False)),
                ('nivel', models.CharField(choices=[('Facil', 'Fácil'), ('Intermedio', 'Intermedio'), ('Dificil', 'Difícil')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Grado',
            fields=[
                ('id_grado', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_grado', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='NivelAcademico',
            fields=[
                ('id_nivel_academico', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
                ('fecha_nacimiento', models.DateField()),
                ('correo', models.EmailField(max_length=254, unique=True)),
                ('contrasena', models.CharField(max_length=255)),
                ('tipo_cuenta', models.CharField(choices=[('estudiante', 'Estudiante'), ('padre', 'Padre'), ('apoderado', 'Apoderado'), ('normal', 'Normal')], max_length=20)),
                ('pfp', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id_curso', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=255)),
                ('id_grado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_api.grado')),
            ],
        ),
        migrations.CreateModel(
            name='Leccion',
            fields=[
                ('id_leccion', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=255)),
                ('descripcion', models.TextField()),
                ('puntos_obtenidos', models.DecimalField(decimal_places=2, max_digits=10)),
                ('orden', models.IntegerField()),
                ('id_nivel_dificultad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_api.dificultad')),
            ],
        ),
        migrations.AddField(
            model_name='grado',
            name='id_nivel_academico',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_api.nivelacademico'),
        ),
        migrations.CreateModel(
            name='Pregunta',
            fields=[
                ('id_pregunta', models.AutoField(primary_key=True, serialize=False)),
                ('enunciado', models.CharField(max_length=255)),
                ('respuesta_correcta', models.CharField(max_length=255)),
                ('id_leccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_api.leccion')),
            ],
        ),
        migrations.CreateModel(
            name='Intento',
            fields=[
                ('id_intento', models.AutoField(primary_key=True, serialize=False)),
                ('respuesta_seleccionada', models.CharField(max_length=255)),
                ('es_correcta', models.BooleanField()),
                ('id_pregunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_api.pregunta')),
            ],
        ),
        migrations.CreateModel(
            name='Tema',
            fields=[
                ('id_tema', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=255)),
                ('id_curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_api.curso')),
            ],
        ),
        migrations.AddField(
            model_name='leccion',
            name='id_tema',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_api.tema'),
        ),
        migrations.CreateModel(
            name='RankingUsuario',
            fields=[
                ('id_ranking', models.AutoField(primary_key=True, serialize=False)),
                ('puntos_totales', models.IntegerField()),
                ('posicion', models.IntegerField()),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_api.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='PuntoUsuario',
            fields=[
                ('id_punto', models.AutoField(primary_key=True, serialize=False)),
                ('puntos_obtenidos', models.IntegerField()),
                ('motivo', models.CharField(max_length=255)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('id_leccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_api.leccion')),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_api.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='ProgresoUsuario',
            fields=[
                ('id_progreso', models.AutoField(primary_key=True, serialize=False)),
                ('completado', models.BooleanField()),
                ('fecha_completado', models.DateTimeField(blank=True, null=True)),
                ('id_leccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_api.leccion')),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_api.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='IntentoUsuario',
            fields=[
                ('id_intento_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('id_intento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_api.intento')),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_api.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='UsuarioGrado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('id_grado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_api.grado')),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_api.usuario')),
            ],
            options={
                'unique_together': {('id_usuario', 'id_grado')},
            },
        ),
    ]
